### PR TITLE
add cmake

### PR DESCRIPTION
**Pull request by tomszosz**
new system packages: 
- cmake

new R packages: 
- nloptr, 
- pbkrtest

### CODE REVIEW

**Review by dinakar29 — APPROVED** [review]
LGTM

**Comment by dinakar29** [comment]
Let's also add the `car` package to the packages list for `rstudio` and `rstudio-local` images, as it'll save installation time.

**Comment by tomszosz** [comment]
> Let's also add the `car` package to the packages list for `rstudio` and `rstudio-local` images, as it'll save installation time.
is is already in main branch
https://github.com/insightsengineering/ci-images/blob/main/dockerfiles/scripts/install_cran_pkgs.R#L39
https://github.com/insightsengineering/ci-images/blob/main/dockerfiles/scripts/install_cran_pkgs.R#L158

**Comment by tomszosz** [comment]
I can add `nloptr', `pbkrtest`
```
Installing 5 packages: nloptr, lme4, pbkrtest, lmerTest, car
```

**Pull request merged**
