### PR TITLE
New images for CRAN emulations

### PR DESCRIPTION
**Pull request by cicdguy**
Adds Debian and Fedora images which will be used for CRAN emulations.

### CODE REVIEW

**Review by walkowif — APPROVED** [review]
LGTM

**Comment by gowerc** [comment]
@cicdguy  @walkowif ,

If I'm reading this right it looks like you are using the rhub images as your backbone.  I just wanted to say that our big issue was that the rhub issues don't really track the CRAN machines that well particularly the fedora machines. In particular CRAN is using  fedora 36 + clang 15  whilst rhub is using fedora33 + clang 11.   This meant we were getting issues on CRAN that we weren't able to reproduce on rHub. I posted an issue about this here:
https://github.com/r-hub/rhub-linux-builders/issues/63

**Comment by gowerc** [comment]
Thus was the basis for my request if we could develop our own internal images that more closely aligned with CRAN's. Even if it was only just for some of the more problematic ones like their fedora and debian machines.

**Comment by gowerc** [comment]
Makes sense to me :)

**Pull request merged**
